-- Crea las tablas de tags y relación carta-tags, y siembra el catálogo base.

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS tags (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL UNIQUE,
  nombre TEXT NOT NULL,
  categoria TEXT,
  descripcion TEXT
);

CREATE TABLE IF NOT EXISTS carta_tags (
  carta_id INTEGER NOT NULL,
  tag_id INTEGER NOT NULL,
  PRIMARY KEY (carta_id, tag_id),
  FOREIGN KEY (carta_id) REFERENCES cartas(id) ON DELETE CASCADE,
  FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
);

-- Semilla de catálogo base (INSERT OR IGNORE evita duplicados si ya existen).
INSERT OR IGNORE INTO tags (slug, nombre, categoria, descripcion) VALUES
  ('imbloqueable', 'Imbloqueable', 'defensivo', NULL),
  ('indesterrable', 'Indesterrable', 'defensivo', 'Inmune a efectos de destierro'),
  ('indestructible', 'Indestructible', 'defensivo', NULL),
  ('inmunidad', 'Inmunidad', 'defensivo', 'Inmunidad a efectos definidos en la habilidad'),
  ('sacrifica', 'Sacrifica para pagar', 'coste', 'Coste de destruir propia'),
  ('descarta_para_pagar', 'Descarta para pagar', 'coste', NULL),
  ('exilia_para_pagar', 'Exilia para pagar', 'coste', NULL),
  ('revela_para_pagar', 'Revela para pagar', 'coste', NULL),
  ('elige_coste', 'Elige un coste', 'coste', NULL),
  ('roba_cartas', 'Roba cartas', 'recursos', NULL),
  ('bota_cartas', 'Muele mazo oponente', 'control', 'Descarta desde mazo del oponente'),
  ('descarta_mano', 'Descarta de mano', 'control', NULL),
  ('destruye_objetivo', 'Destruye objetivo', 'removal', NULL),
  ('destierra_objetivo', 'Destierra objetivo', 'removal', NULL),
  ('hace_dano', 'Hace daño', 'ofensivo', NULL),
  ('restriccion', 'Restricción/regla', 'control', NULL),
  ('no_agrupable', 'No puede ser agrupado', 'control', 'Restringe que se agrupe'),
  ('no_reagrupable', 'No puede ser reagrupado', 'control', NULL),
  ('no_barajable', 'No puede ser barajado', 'control', NULL),
  ('no_tap', 'No puede girarse', 'defensivo', NULL),
  ('no_puede_atacar', 'No puede atacar', 'restriccion', NULL),
  ('no_puede_bloquear', 'No puede bloquear', 'restriccion', NULL),
  ('debe_atacar', 'Debe atacar', 'restriccion', NULL),
  ('debe_bloquear', 'Debe bloquear', 'restriccion', NULL),
  ('apresurado', 'Puede atacar al entrar', 'ofensivo', 'Haste'),
  ('no_anulable', 'No puede ser anulado', 'defensivo', NULL),
  ('no_pierde_habilidad', 'No puede perder habilidades', 'defensivo', NULL),
  ('sin_bonus_fuerza', 'No recibe bonus de fuerza', 'restriccion', NULL),
  ('no_sale_juego', 'No puede salir del juego', 'defensivo', NULL),
  ('no_puede_ser_declarado_atacante', 'No puede ser declarado atacante', 'restriccion', NULL),
  ('no_puede_ser_declarado_bloqueador', 'No puede ser declarado bloqueador', 'restriccion', NULL),
  ('puede_ser_declarado_atacante', 'Puede ser declarado atacante', 'soporte', NULL),
  ('puede_ser_declarado_bloqueador', 'Puede ser declarado bloqueador', 'soporte', NULL),
  ('puede_bloquear', 'Puede bloquear', 'soporte', NULL),
  ('bloquea_multiple', 'Puede bloquear múltiples', 'soporte', NULL),
  ('bloquea_imbloqueables', 'Puede bloquear imbloqueables', 'soporte', NULL),
  ('equipa_armas_extra', 'Puede equipar armas extra', 'soporte', NULL),
  ('busca_mazo', 'Busca en mazo', 'tutor', NULL),
  ('regresa_cementerio', 'Recupera del cementerio/baraja', 'recursos', NULL),
  ('previene_dano', 'Previene daño', 'defensivo', NULL),
  ('genera_recursos', 'Genera recursos', 'recursos', NULL),
  ('baraja', 'Baraja cartas', 'control', NULL),
  ('mira_mazo', 'Mira/Reordena mazo', 'control', NULL),
  ('revela_superior', 'Revela carta(s) superior(es)', 'control', NULL),
  ('mira_mano_oponente', 'Mira mano oponente', 'control', NULL),
  ('anula', 'Anula efectos/talismanes', 'control', NULL),
  ('copia_habilidad', 'Copia habilidad/efecto', 'soporte', NULL),
  ('gana_habilidad', 'Confiere habilidad', 'soporte', NULL),
  ('pierde_habilidad', 'Quita habilidad', 'control', NULL),
  ('modifica_fuerza', 'Modifica fuerza', 'soporte', NULL),
  ('modifica_coste', 'Modifica coste', 'soporte', NULL),
  ('modifica_raza', 'Modifica raza', 'soporte', NULL),
  ('modifica_tipo', 'Modifica tipo', 'soporte', NULL),
  ('modifica_regla', 'Modifica regla', 'soporte', NULL),
  ('mueve_zona', 'Mueve zona', 'soporte', 'Mover entre juego, cementerio, exilio, mano, mazo'),
  ('pone_en_juego', 'Pone en juego', 'soporte', NULL),
  ('redirige_objetivo', 'Redirige objetivo', 'control', NULL),
  ('limpia_mods', 'Limpia modificadores', 'control', NULL),
  ('salta_fase', 'Salta fases', 'control', NULL),
  ('tap', 'Gira/Inhabilita', 'control', NULL),
  ('trigger_al_entrar', 'Trigger al entrar en juego', 'triggers', NULL),
  ('trigger_al_salir', 'Trigger al salir de juego', 'triggers', NULL),
  ('trigger_al_atacar', 'Trigger al atacar', 'triggers', NULL),
  ('trigger_al_bloquear', 'Trigger al bloquear', 'triggers', NULL),
  ('trigger_fin_turno', 'Trigger al fin de turno', 'triggers', NULL),
  ('trigger_inicio_turno', 'Trigger al inicio de turno', 'triggers', NULL),
  ('trigger_recibe_dano', 'Trigger al recibir daño', 'triggers', NULL),
  ('trigger_destruido', 'Trigger al ser destruido', 'triggers', NULL),
  ('trigger_juega_carta', 'Trigger al jugar carta', 'triggers', NULL),
  ('trigger_descarta', 'Trigger al descartar', 'triggers', NULL),
  ('una_vez_por_turno', 'Limitado por turno', 'triggers', NULL),
  ('opcional', 'Efecto opcional', 'triggers', 'Texto incluye “puedes”');


